# Generated by Django 5.2.1 on 2025-05-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artiste_type', to='catalogue.artist', verbose_name='Artiste'),
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artiste_type', to='catalogue.type', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='artisttypeshow',
            name='artist_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='catalogue.artisttype', verbose_name='Artiste + Type'),
        ),
        migrations.AlterField(
            model_name='artisttypeshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artiste_type_links', to='catalogue.show', verbose_name='Spectacle'),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Slug'),
        ),
    ]
