# Generated by Django 5.2.1 on 2025-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_artist_first_name_alter_artist_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
