# Generated by Django 5.2.1 on 2025-05-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_troupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='troupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='catalogue.troupe'),
        ),
    ]
